import type { Recommendation } from '@/types/telemetry';

export function buildReviewPacket(rec: Recommendation, note: string): string {
  const missing = rec.checklist.filter((item) => !item.complete);
  const complete = rec.checklist.filter((item) => item.complete);

  const lines: string[] = [
    'REVIEW PACKET',
    '=============',
    '',
    `Task: ${rec.title}`,
    `Task ID: ${rec.id}`,
    `Generated: ${new Date().toLocaleString()}`,
    `Category: ${rec.category}    Priority: ${rec.priority}`,
    `Relevant roles: ${rec.roles.join(', ')}`,
    '',
    'SUMMARY',
    '-------',
    rec.description,
    `Recommended action: ${rec.action}`,
    '',
    'SOURCE CHECKLIST / VALIDATION',
    '-----------------------------',
    ...rec.checklist.map((item) => `[${item.complete ? 'x' : ' '}] ${item.label}`),
    '',
    `Status: ${complete.length}/${rec.checklist.length} sources verified`,
    '',
    'VALIDATION WARNINGS / MISSING FIELDS',
    '-------------------------------------',
    ...(missing.length === 0
      ? ['None — all required sources are present.']
      : missing.map((item) => `WARNING: missing — ${item.label}`)),
    '',
    'REVIEWER NOTES',
    '--------------',
    note.trim() ? note.trim() : 'No notes added.',
    '',
    '---',
    'Generated by Adaptive AI Workspace',
  ];

  return lines.join('\n');
}

export function downloadReviewPacket(rec: Recommendation, note: string): void {
  const content = buildReviewPacket(rec, note);
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `review-packet-${rec.id}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
