import type { Recommendation } from '@/types/telemetry';
import type { ChecklistRecord } from '@/lib/profile';

export function buildReviewPacket(rec: Recommendation, note: string): string {
  const missing = rec.checklist.filter((item) => !item.complete);
  const complete = rec.checklist.filter((item) => item.complete);

  const lines: string[] = [
    'REVIEW PACKET',
    '=============',
    '',
    `Task: ${rec.title}`,
    `Task ID: ${rec.id}`,
    `Generated: ${new Date().toLocaleString()}`,
    `Category: ${rec.category}    Priority: ${rec.priority}`,
    `Relevant roles: ${rec.roles.join(', ')}`,
    '',
    'SUMMARY',
    '-------',
    rec.description,
    `Recommended action: ${rec.action}`,
    '',
    'SOURCE CHECKLIST / VALIDATION',
    '-----------------------------',
    ...rec.checklist.map((item) => `[${item.complete ? 'x' : ' '}] ${item.label}`),
    '',
    `Status: ${complete.length}/${rec.checklist.length} sources verified`,
    '',
    'VALIDATION WARNINGS / MISSING FIELDS',
    '-------------------------------------',
    ...(missing.length === 0
      ? ['None — all required sources are present.']
      : missing.map((item) => `WARNING: missing — ${item.label}`)),
    '',
    'REVIEWER NOTES',
    '--------------',
    note.trim() ? note.trim() : 'No notes added.',
    '',
    '---',
    'Generated by Adaptive AI Workspace',
  ];

  return lines.join('\n');
}

// Same packet shape as buildReviewPacket, but built from a raw
// recommendation_checklists row (the shape returned by fetchVisibleChecklists)
// rather than the in-memory Recommendation the Dashboard generates live. Used
// by the Oversight page, where an oversight-role viewer may be exporting a
// packet for a record that isn't their own.
export function buildChecklistRecordPacket(rec: ChecklistRecord, viewerId: string): string {
  const missing = rec.checklist.filter((item) => !item.complete);
  const complete = rec.checklist.filter((item) => item.complete);
  const isOwn = rec.user_id === viewerId;

  const lines: string[] = [
    'REVIEW PACKET',
    '=============',
    '',
    `Task: ${rec.title}`,
    `Task ID: ${rec.recommendation_id}`,
    `Record owner: ${isOwn ? 'you' : `another user (${rec.user_id.slice(0, 8)})`}`,
    `Generated: ${new Date().toLocaleString()}`,
    `Last updated: ${new Date(rec.updated_at).toLocaleString()}`,
    `Relevant roles: ${rec.roles.length ? rec.roles.join(', ') : 'none recorded'}`,
    '',
    'SOURCE CHECKLIST / VALIDATION',
    '-----------------------------',
    ...rec.checklist.map((item) => `[${item.complete ? 'x' : ' '}] ${item.label}`),
    '',
    `Status: ${complete.length}/${rec.checklist.length} sources verified (${rec.complete_count}/${rec.total_count} recorded)`,
    '',
    'VALIDATION WARNINGS / MISSING FIELDS',
    '-------------------------------------',
    ...(missing.length === 0
      ? ['None — all required sources are present.']
      : missing.map((item) => `WARNING: missing — ${item.label}`)),
    ...(rec.is_complete !== (missing.length === 0)
      ? ['WARNING: stored completion flag disagrees with checklist contents.']
      : []),
    '',
    'REVIEWER NOTES',
    '--------------',
    rec.notes.trim() ? rec.notes.trim() : 'No notes added.',
    '',
    '---',
    'Generated by Adaptive AI Workspace',
    isOwn ? '' : `Viewed under an oversight role by a different account than the record owner.`,
  ].filter((line) => line !== undefined);

  return lines.join('\n');
}

export function downloadChecklistRecordPacket(rec: ChecklistRecord, viewerId: string): void {
  const content = buildChecklistRecordPacket(rec, viewerId);
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `review-packet-${rec.recommendation_id}-${rec.user_id.slice(0, 8)}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadReviewPacket(rec: Recommendation, note: string): void {
  const content = buildReviewPacket(rec, note);
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `review-packet-${rec.id}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
